<?php

namespace Mkk\SiteBundle\Repository;

use Doctrine\ORM\Query;
use Mkk\SiteBundle\Lib\LibRepository;

/**
 * HoraireRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryAdresse extends LibRepository
{
    /**
     * requete pour la liste d'admin.
     *
     * @return Query
     */
    public function searchAdminList(): Query
    {
        $code   = $this->getEntityName();
        $entity = "{$this->bundle}:Adresse";
        $dql    = "SELECT {$code} FROM {$entity} {$code}";
        $query  = $this->getQuery($dql);

        return $query;
    }

    /**
     * Retour les lignes à modifier.
     *
     * @param string $field champs
     *
     * @return array
     */
    public function commandFind($field): array
    {
        $code   = $this->getEntityName();
        $entity = "{$this->bundle}:Adresse";
        $em     = $this->getEntityManager();
        $dql    = "SELECT {$code} FROM {$entity} {$code} LEFT JOIN {$code}.{$field} field WHERE field.id IS NOT NULL";
        $result = $em->createQuery($dql)->getResult();

        return $result;
    }
}
