<?php

namespace Mkk\SiteBundle\Repository;

use Doctrine\ORM\Query;
use Mkk\SiteBundle\Lib\LibRepository;

/**
 * HoraireRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryNafSousClasse extends LibRepository
{
    /**
     * Backend.
     *
     * @param mixed $data data
     *
     * @return array
     */
    public function searchNafSousClasse($data): Query
    {
        $code   = $this->getEntityName();
        $entity = "{$this->bundle}:NafSousClasse";
        $dql    = "SELECT {$code} FROM {$entity} {$code}";
        $search = [];
        if (isset($data['lettre'])) {
            $lettre   = $data['lettre'];
            $search[] = "({$code}.libelle LIKE '%{$lettre}%' OR {$code}.code LIKE '%{$lettre}%')";
        }

        $dql    = $this->searchImplode($search, $dql);
        $dql    = trim($dql) . " ORDER BY {$code}.code ASC";
        $result = $this->setSearchResult($dql);

        return $result;
    }
}
