<?php

namespace Mkk\SiteBundle\Repository;

use Mkk\SiteBundle\Lib\LibTranslatableRepository;

/**
 * MenuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryMenu extends LibTranslatableRepository
{
}
