<?php

namespace Mkk\SiteBundle\Repository;

use Mkk\SiteBundle\Lib\LibRepository;

/**
 * EmplacementRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryEmplacement extends LibRepository
{
}
