<?php

namespace Mkk\SiteBundle\Repository;

use Doctrine\ORM\Query;
use Mkk\SiteBundle\Lib\LibRepository;

/**
 * TagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryTag extends LibRepository
{
    /**
     * requete pour la liste d'admin.
     *
     * @param array $data data
     *
     * @return Query
     */
    public function searchAdminList($data = []): Query
    {
        $entity = $this->getEntityName();
        $dql    = "SELECT {$entity} FROM {$this->bundle}:Tag {$entity}";
        if (isset($data['type'])) {
            $type = $data['type'];
            $dql  = "{$dql} WHERE {$entity}.totalnb{$type}!=0";
        }

        $query = $this->getQuery($dql);

        return $query;
    }
}
