<?php

namespace Mkk\SiteBundle\Repository;

use Mkk\SiteBundle\Lib\LibRepository;

/**
 * HoraireRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryNafClasse extends LibRepository
{
}
