<?php

namespace Mkk\SiteBundle\Repository;

use Doctrine\ORM\Query;
use Mkk\SiteBundle\Lib\LibTranslatableRepository;

/**
 * MetarianeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryMetariane extends LibTranslatableRepository
{
    /**
     * requete pour la liste d'admin.
     *
     * @return Query
     */
    public function searchAdminList(): Query
    {
        $entity = $this->getEntityName();
        $dql    = "SELECT {$entity} FROM {$this->bundle}:Metariane {$entity}";
        $query  = $this->getQuery($dql);

        return $query;
    }

    /**
     * requete pour la liste d'admin.
     *
     * @param array $data liste des routes en fonction
     *
     * @return array
     */
    public function supprimer(array $data = []): array
    {
        $entity  = $this->getEntityName();
        $dql     = "SELECT {$entity} FROM {$this->bundle}:Metariane {$entity}";
        $implode = implode("','", $data);
        $implode = "'{$implode}'";
        $dql     = "{$dql} WHERE {$entity}.route NOT IN ";
        $dql     = "{$dql} ({$implode})";

        $query  = $this->getQuery($dql);
        $result = $query->getResult();

        return $result;
    }
}
