<?php

namespace Mkk\SiteBundle\Repository;

use Doctrine\ORM\Query;
use Mkk\SiteBundle\Lib\LibTranslatableRepository;

/**
 * HoraireRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryGroup extends LibTranslatableRepository
{
    /**
     * Backend.
     *
     * @param mixed $data data
     *
     * @return array
     */
    public function searchGroupAll($data): Query
    {
        $code   = $this->getEntityName();
        $entity = "{$this->bundle}:Group";
        $dql    = "SELECT {$code} FROM {$entity} {$code}";
        if (isset($data['lettre'])) {
            $lettre = $data['lettre'];
            $dql    = "{$dql} WHERE {$code}.nom LIKE '%{$lettre}%'";
        }

        $result = $this->setSearchResult($dql);

        return $result;
    }

    /**
     * requete pour la liste d'admin.
     *
     * @return Query
     */
    public function searchAdminList(): Query
    {
        $entity = $this->getEntityName();
        $dql    = "SELECT {$entity} FROM {$this->bundle}:Group {$entity}";
        $query  = $this->getQuery($dql);

        return $query;
    }
}
