<?php

namespace Mkk\SiteBundle\Repository;

use Doctrine\ORM\Query;
use Mkk\SiteBundle\Lib\LibTranslatableRepository;

/**
 * CategorieRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryCategorie extends LibTranslatableRepository
{
    /**
     * requete pour la liste d'admin.
     *
     * @param array $data data
     *
     * @return Query
     */
    public function searchAdminList($data = []): Query
    {
        $entity = $this->getEntityName();
        $params = [];
        $dql    = "SELECT {$entity} FROM {$this->bundle}:Categorie {$entity}";
        if (isset($data['type'])) {
            $type           = $data['type'];
            $dql            = "{$dql} WHERE {$entity}.type=:type";
            $params['type'] = $type;
        }

        $query = $this->getQuery($dql)->setParameters($params);

        return $query;
    }
}
