services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Mkk\PublicBundle\:
        resource: "../../*"

#    mkk_public.example:
#        class: Mkk\PublicBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
